---
title: "Trends in I-O Psychology"
output: rmarkdown::github_document
---

# Trends in Industrial-Organizational Psychology

As scientists look for new empirical insights in the world of industrial-organizational (I–O) psychology, topics inevitably fall in and out of vogue.  Perhaps the most volatile and well recognized shifts have been observed among the personality research domain. Namely, Walter Mischel’s 1968 book *Personality and Assessment* gloomy concluded: "\[w\]ith the possible exception of intelligence, highly generalized behavioral consistencies have not been demonstrated, and the concept of personality traits as broad response predispositions is thus untenable."  After this book was published, personality research considerably declined for the following decade.  Identifying such research trends (and slumps) helps researchers and practitioners determine where the field has been and is headed in addition to identify ideas and topics that warrant empirical investigations and/or should be reexamined.

This Shiny app (https://doi.org/10.1080/08959285.2020.1751165) was designed to help researchers and practitioners identify current trends in I–O psychology.  It uses user-specified queries to search peer-reviewed article abstracts in I-O psychology's top scientific journals (see Aguinis et al., 2017).  Search results are plotted over time, and users are able to narrow down specific journals and download a .csv file of their generated data.  Additionally, search results are used to predict citation rates across decades. Feel free to download and adapt the app to your needs or submit a request.

## System Requirements

In addition to R and RStudio, this app requires the following packages:

1. shiny
2. shinyBS
3. shinydashboard
4. tidyverse
5. tidytext
6. plotly
7. knitr
8. vroom

Dependencies can be easily installed and loaded via the following `R` code.

``` r
source("https://raw.githubusercontent.com/zktraylor/trends_in_io/master/install_dependencies.R")
```

## Running the Shiny App

Clone/download the Github repository (e.g., download as .zip) and run the following code in your RStudio console.

``` r
# clone/download file
# will be saved and named `~/trends_in_io-master`
# set as working directory and run/start Shiny app
setwd("~/Downloads/trends_in_io-master")
runApp()
```
